package HT2022.test;
// Generated by ComTest BEGIN
import HT2022.*;
import static org.junit.Assert.*;
import org.junit.*;
import static HT2022.Harjoitusaika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.21 16:20:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HarjoitusaikaTest {



  // Generated by ComTest BEGIN
  /** testLueHarjoitusaika174 */
  @Test
  public void testLueHarjoitusaika174() {    // Harjoitusaika: 174
    String s1 = "30.8.2022,19:00,Isosali 4.krs,100,1002,20"; 
    Relaatiot r1 = new Relaatiot(); 
    String lajiString  ="Brasilialainen jujitsu,Valkoinen vyö:Sininen vyö:Purppura vyö:Ruskea vyö:Musta vyö,1"; 
    Laji l = Laji.lueLaji(lajiString); 
    Lajit lajit = new Lajit(); 
    lajit.add(l); 
    Harjoitusaika ha = lueHarjoitusaika(s1,  r1, lajit); 
    assertEquals("From: Harjoitusaika line: 186", "30.8.2022 19:00 Brasilialainen jujitsu", ha.toString()); 
    assertEquals("From: Harjoitusaika line: 187", "Isosali 4.krs", ha.getSali()); 
    assertEquals("From: Harjoitusaika line: 189", "Brasilialainen jujitsu", ha.getLaji().toString()); 
  } // Generated by ComTest END
}