package HT2022.test;
// Generated by ComTest BEGIN
import HT2022.*;
import static org.junit.Assert.*;
import org.junit.*;
import static HT2022.Henkilo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.21 16:49:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkiloTest {


  // Generated by ComTest BEGIN
  /** testLueHenkilo198 */
  @Test
  public void testLueHenkilo198() {    // Henkilo: 198
    String s1 = "Sami,Joukainen,15.10.2000,Savikuja 6,00100,Helsinki"; 
    Relaatiot r1= new Relaatiot(); 
    Henkilo h1 = lueHenkilo(s1, r1); 
    assertEquals("From: Henkilo line: 204", true, h1 != null); 
    String s2 ="Timo,Karhu,1.7.1977,Toripolku 6 d 3,00760,Helsinki"; 
    Henkilo h2 = lueHenkilo(s2, r1); 
    assertEquals("From: Henkilo line: 208", "Timo Karhu", h2.toString()); 
    assertEquals("From: Henkilo line: 210", "1 : 1000 : 0 : 0", Relaatiot.getRelaatioIdlla(1).toString());
  } // Generated by ComTest END
}