package HT2022.test;
// Generated by ComTest BEGIN
import HT2022.*;
import static org.junit.Assert.*;
import org.junit.*;
import static HT2022.Laji.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.21 16:48:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LajiTest {



  // Generated by ComTest BEGIN
  /** testLueLaji103 */
  @Test
  public void testLueLaji103() {    // Laji: 103
    String s  ="Brasilialainen jujitsu,Valkoinen vyö:Sininen vyö:Purppura vyö:Ruskea vyö:Musta vyö,1"; 
    Laji l = lueLaji(s); 
    assertEquals("From: Laji line: 109", true, l.getVisible()); 
    assertEquals("From: Laji line: 110", "Brasilialainen jujitsu", l.getLaji());
    assertEquals("From: Laji line: 111", 100, l.getLajiId()); 
    String s2 ="Judo,Aloittelija:Harrastaja:Kilpa,0"; 
    Laji l2 = lueLaji(s2); 
    assertEquals("From: Laji line: 115", "Judo", l2.toString());
    assertEquals("From: Laji line: 116", false, l2.getVisible()); 
    assertEquals("From: Laji line: 117", "[Aloittelija, Harrastaja, Kilpa]", l2.getTasot().toString()); 
    assertEquals("From: Laji line: 118", 101, l2.getLajiId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTestiTesti147 */
  @Test
  public void testTestiTesti147() {    // Laji: 147
    assertEquals("From: Laji line: 148", 3, testiTesti(1,2)); 
    assertEquals("From: Laji line: 149", -3, testiTesti(-1,-2));
  } // Generated by ComTest END
}